variables:
  - template: pipeline-templates/global-variables.yml
trigger:
  branches:
    include:
      - master
      - release-*
  paths:
    exclude:
      - README.md
pr: none
jobs:
  - job: Build
    displayName: "Build PowerShell module and publish to PowerShell Gallery"
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: pipeline-templates/build-windows-steps.yml
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'OneIdentity.RD.SBox.Safeguard-ServiceConnection'
          KeyVaultName: 'SafeguardBuildSecrets'
          SecretsFilter: 'PowerShellGalleryApiKey'
        displayName: 'Get PowerShell Gallery API key from Sandbox Azure Key Vault'
      - task: PowerShell@2
        inputs:
          targetType: inline
          failOnStderr: true
          script: |
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            Install-PackageProvider Nuget –Force
            Get-PSRepository
            Publish-Module -Name safeguard-discovery -NuGetApiKey "$(PowerShellGalleryApiKey)" -Verbose -SkipAutomaticTags -Force
        displayName: 'Publish PowerShell module to PowerShell Gallery'
